/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.operators.doNotEdit;

import com.example.operators.editHere.OperatorLogic;

/* ### READ CAREFULLY! ###
 * Instructions:
 * 
 * Do not edit the main method!
 * Do not edit anything else than the methods:
 *  - checkForAge(...)
 *  - checkForCitizenship(...)
 *  - checkFor
 */

public class App {
    public static void main(String[] args) {
        // **** DO NOT EDIT THE MAIN METHID CODE ****
        // **** ONLY EDIT THE FUNCTIONS LIKE "checkForCitizenship(...)" or
        // "checkForAge(...)" ****
        System.out.print("Enter your age: ");
        int age = InputScanner.scanForAge();

        System.out.print("Are you a citizen? (true/false): ");
        boolean isCitizen = InputScanner.scanForIsCitizen();

        OperatorLogic.printOutput(age, isCitizen);
        // *****************************************
    }
}
